spring.application.name=emailauth
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_ywhf4Xz9iVTD@ep-frosty-night-ay3nu6ey-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_ywhf4Xz9iVTD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect